### ISSUE TITLE
Missing _service in checkJob  

### ISSUE THREAD

**Issue by pauldzy** [jgravois/esri-leaflet-gp#13]
Hi John,

Not sure how collaborative the Esri stuff is in terms of pull requests.  I noticed that async checkJob fails rather spectacularly for me calling the original request over and over 1000 times.  

https://github.com/pauldzy/esri-leaflet-gp/commit/5273b39d4e160aabff2cb4a780f69cdc751e9e65#diff-60de9bcd07cafff987c786382ec79430

Cheers,
Paul

**Comment by jgravois** [comment]
closed by 5273b39d4e160aabff2cb4a780f69cdc751e9e65
