### ISSUE TITLE
General issues regarding gp output handling

### ISSUE THREAD

**Issue by pauldzy** [jgravois/esri-leaflet-gp#15]
Thanks John for replying so fast to my first issue.    

So I cobbled together a quick example here 
http://codepen.io/pauldzy/pen/mJWxXg
using a 10.3 geoprocessing service created from a Python toolbox hosted here
http://industux.induscorp.com/arcgis/rest/services/WATERS_SERVICES/GPServer/PointIndexingService

So this geoprocessing service does not come with a OutputProfile endpoint and I do not know how to activate such a thing or what causes it to come into existence.  Rather my results summary comes back here
http://industux.induscorp.com/arcgis/rest/services/WATERS_SERVICES/GPServer/PointIndexingService/jobs/j75801ffbe14d4efcae31298e932ec70b?f=pjson
and then I need to drill in via the output parameter name to get the results I want
http://industux.induscorp.com/arcgis/rest/services/WATERS_SERVICES/GPServer/PointIndexingService/jobs/j75801ffbe14d4efcae31298e932ec70b/results/pFlowlines?f=pjson

So I am not sure if my type of gp service really is meant for use with your code.  At the very least some kind of replacement for the hard coded OutputProfile thing would be needed.  

Cheers,
Paul

**Comment by jgravois** [comment]
no worries.  im out of the office right now, but i'll take a look at this and get back to you soon.

**Comment by jgravois** [comment]
@pauldzy let me know if you have any trouble implementing my fix.  in general you now just have to set Task.[setOutputParam('<yourownparamname>')](https://github.com/jgravois/esri-leaflet-gp/blob/master/debug/async-sample.html#L58) to let the plugin know how to retrieve the featureeset output.
