### ISSUE TITLE
handle GP services that respond with multiple output parameters

### ISSUE THREAD

**Issue by pauldzy** [jgravois/esri-leaflet-gp#21]
Hi John,

Thanks for all the Sunday work, that solved a lot of issues for me.  I know your architecture assumes a single output parameter for all services.  The thing is I don't really have many services that match that expectation.  For this service in question, there are four outputs but for my CodePen example I only visualize one and sniff scalars from the other.  

I am not sure if you are interested in providing a way to grab multiple outputs but at the very least could you persist and provide the jobID and jobStatus in some manner?  Currently the response to the run is the one output parameter load that lacks these items.  With the JobID and the certainty the job succeeded, its easy enough to hit the endpoint myself for secondary parameters.

A secondary minor issue is the delay and the total loop count for the job success check.  In my environment, EPA production servers can take several minutes or more to produce results and hitting AGS so frequently is just overkill.  Could these items be tunable by the user?

Thanks,
Paul

**Comment by jgravois** [comment]
these are really good suggestions! you might already know this, but you can access the raw service response in the [callback](https://github.com/jgravois/esri-leaflet-gp/blob/master/debug/async-sample.html#L69).  i hadn't thought about it much, but halfway thought the `jobId` would show up there.  since it doesn't, i don't see a problem with tacking it onto the parsed response.

i'm not sure i understand the point of explicitly passing `jobStatus`. what would it be helpful for?

with regard to making the interval of requesting status updates from the service configurable, sounds great.

- [ ] attach `jobId` to parsed responses
- [ ] make async status request interval configurable

**Comment by jgravois** [comment]
forgot to respond to the major suggestion.  i'm interested in adding support for multiple outputs.  i'll take a look at your codepen sample and try and figure out exactly what it'll take.

**Comment by pauldzy** [comment]
Hi John,

Again thanks for the quick response.  I am not really sure of the scope of your code so apologies for throwing stuff at you.  Knowing jobStatus is perhaps unnecessary but its based on a vague paranoia that the service may not have completed successfully.  I suppose I am more used to a pattern where errors are sent to a separate callback - there are a lot of things that could go wrong with an async service.  In this case it all comes back in the response and sniffing for jobStatus would be a very simple way in a failed status to know if the job itself failed or was still executing and the loop ran out or what.  It's not a critical thing.  

In terms of multiple outputs, I guess as I mentioned I would like the option of fetching some outputs and not others, also - sorry if this is picky - the outputs from my services can be quite large in some cases and sometimes I don't actually need them as GeoJSON, they populate tables or perhaps are fed into a second Esri service.  Having the option to skip the GeoJSON conversion would be swell.

Any finally the next idea is how to gracefully chain together service calls.  Having the option to load parameters as a single associative array would be useful.

So thanks for your attention, this is a great library.  EPA is quite focused on AGOL development and utilizing existing AGS servers with AGOL.  The leaflet library is great way for me to decouple the AGS services from the ever-developing and sometimes a bit unstable AGOL environment.  I can remain in my backend spider hole and say, "hey look, this works fine in leaflet, think about what you can do in AGOL" and pass it on to others.

Cheers,
Paul

**Comment by jgravois** [comment]
> I am more used to a pattern where errors are sent to a separate callback
this pattern *should* give you access to a **parsed response**, **raw response** and **caught errors** in a single callback.

> I would like the option of fetching some outputs and not others
building your logic on top of a reference to the raw response would be appropriate for this.  let me know if something is missing or not working.

> I can remain in my backend spider hole
hah.

**Comment by pauldzy** [comment]
Hi John,
I was looking at your changes this morning.  So I have been using your example pattern of a callback e.g.

function callback(error, geojson, response)

So the jobID gets attached to the geojson (parsed) object and not the full (raw) response object.  I would have almost expected the reverse but this works.  I updated my codepen to use things as they are now.
Thanks,
Paul

**Comment by jgravois** [comment]
yeah, that's because its not present in the final response.  we have to dig it out earlier.  I updated the readme to reflect what you can expect to see in the parsed response.

thanks for testing and providing feedback!

**Comment by jgravois** [comment]
as of version 1.0.1, im parsing and returning parsing multiple output parameters of various types (featuresets, strings, booleans or GPDataFiles).

i'll leave this issue open until if/when the code is refactored to do the same for async services.

**Comment by jgravois** [comment]
resolved in #44. thx to @kgrimsby :tada:!
