### ISSUE TITLE
add support for output image/map services

### ISSUE THREAD

**Issue by rowanwins** [jgravois/esri-leaflet-gp#24]
Hi @jgravois ,

Thanks for an excellent plugin, it looks very promising.

Im just trying to work out how to retrieve a raster map service as the response. 
http://codepen.io/rowanwins/pen/gpRWxW

Im trying to do similiar this example although I only want the raster layer and not the features.
https://developers.arcgis.com/javascript/jssamples/gp_resultmapservice.html

Im just getting a null response back at the moment. Is there a good way to get meaningful errors back from the requests, I've tried error reponse and I just get "Job failed" which doesnt tell me much. Im guessing perhaps I need to do something about with the result object?

Thanks in advance,
Rowan

**Comment by jgravois** [comment]
right now I pretty much only parse GP responses looking for featuresets to convert them to GeoJSON.  that being said, I'm interested in trying to incorporate support for output map services as well.

**Comment by rowanwins** [comment]
Ah ok, thanks @jgravois . Certainly map service outputs would be handy. I'll keep on eye on the plugin as it keep growing. If I were a better developer I'd offer to take a look but Im not quite sure that my skills are there yet!

**Comment by jgravois** [comment]
no need to be shy.  i don't know what the hell i'm doing most of the time either.

**Comment by rowanwins** [comment]
Alright @jgravois I've taken a bit of a look and I think Im making headway, thanks for the encouragement! 

Just a couple of quick q's

1. Should we add an option related to outputType, which defaults to the current setup (geojson), but also accepts MapService?

2. Are the MapServers always parallel to the GPServers? Basically Im trying to work out if we need an option to set the output MapServer or if we cn just work it out based on the GPServer address...
eg
http://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/GPServer
and
http://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/MapServer


Cheers
Rowan

**Comment by rowanwins** [comment]
Gday @jgravois 

I've created a [fork](https://github.com/rowanwins/esri-leaflet-gp) where I've pulled together some working code that I think is actually half-reasonable...

What I've done
1. Created a new Task method for setOutputType which Im setting to 'MapService'
2. In the checkJob function if the outputType is MapService I slightly tweak what happens. The most important thing is I create a  'this.outputMapService' which gives the user a url to use like any other L.esri.dynamicMapLayer
3. I've created a sample file called mapService-example.html where you can see how it all fits together.

Anyway take a look and see what you think. Happy for any feedback. If you're happy to accept it let me know what my next steps are, I think I need to create a pull request or something?

Cheers,
Rowan

PS This was a great learning experience, for the first time in my life I've actually started to understand breakpoints and the source tab in devtools, watch out world!

**Comment by jgravois** [comment]
very cool!  i'll take a look in the next couple days.

**Comment by jgravois** [comment]
rowan, i have a few suggestions:
#### 1. your work needs to be passed in the callback
for consistency, instead of setting the property `this.outputMapService`, the url needs to be made available via the parsed response from the API.
```javascript
callback.call(error, <yourwork>, response);
```

#### 2. avoid the need to declare the output type as "MapService"
it seems to me like it would be ideal if the API *just handled it*.
1. developer tells the API which outputParams to keep track of by name
2. after a job is completed successfully, the API introspects the result and passes back the appropriate value (`boolean`, `string`, `MapService`, `GeoJSON` features) nested in a parsed response

for organization purposes, i think the best idea would be to inject your own code flow within `processGPOutput()`.

#### 3. make sure the new code works with synchronous GP services that output a MapService as well.
i haven't worked with one, but i'm sure its possible to design a GP service this way.

##### for work going forward
the best thing you could do at this point is to create a feature branch to store your work (rather than [commiting directly to master](http://waterstreetgm.org/git-why-you-should-never-commit-directly-to-master/)) and submit a [Pull Request](https://github.com/Esri/developer-support/blob/master/SUBMITPR.md) to this repo so that we can continue the discussion.

##### last, but not least
i really appreciate your help tackling this.  i know it'll take pretty much a complete refactor, but a GP plugin which is capable of returning multiple output types simultaneously from both sync and async services would be a **serious** improvement.

let me know if anything i mentioned above doesn't make sense.

**Comment by rowanwins** [comment]
Hi @jgravois 
Thanks for the feedback. I'll have a shot at incorporating the feedback, I had a feeling you might say something along those lines :)  If you can find a synchronous GP Services that spits out a MapService for testing that would be fab.

Cheers
Rowan

**Comment by jgravois** [comment]
just got confirmation that GP Services **must** be asynchronous in order to output a Map Service, which is nice for us. :smile:

**Comment by rowanwins** [comment]
Gday @jgravois ,

Have hit a bit of a brick wall unfortunantlly and need a hand thinking things through.

Working with this service for example
http://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/GPServer/911%20Calls%20Hotspot

The setOutputParam = Hotspot_Raster    which is equal to the parameter 'name' seen here
http://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/GPServer/911%20Calls%20Hotspot?f=pjson

The problem is that to access the MapService I need a layerID, which in this case equals 1
http://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/MapServer/jobs/j0287a516524544409f4a5e9506961963/1?f=pjson

I could iterate through all the available services but the name of the service does not equal the parameter name set above, for example the name of the Service is 'Hotspot Raster' (see URL above).

It looks like the name of the service is contained back on the original page as 'Display Name' rather than 'name'
http://sampleserver6.arcgisonline.com/arcgis/rest/services/911CallsHotspot/GPServer/911%20Calls%20Hotspot?f=pjson


Urgh its a bit convoluted to explain but hopefully that has made a bit of sense! Any suggestions as to how to best proceed?

Cheers
Rowan

**Comment by jgravois** [comment]
> to access the MapService I need a layerID, which in this case equals 1

i'm not sure i follow you.  dynamic map services are accessed without referencing the index position of individual layers.  i see that in your own sample 'mapService-example.html' you are only interested in displaying layer `1`, but why is that anything the plugin needs to worry about?

> I could iterate through all the available services but the name of the service does not equal the parameter name set above,

again.  i don't follow.  why exactly?  map service job output is accessible via a url dependent on the GP Service name and jobid (as you already demonstrate [here](https://github.com/rowanwins/esri-leaflet-gp/blob/master/src/Tasks/Geoprocessing.js#L184))

i think i'm probably missing something fundamental (ie: you are attempting to access an entirely different output type than you were previously) so im curious to hear more when you have the time.

**Comment by rowanwins** [comment]
Gday @jgravois 
Ok I think Im with you. The thing that still kind of seems weird to me is that to run an asynchronous task you need to define a setOutputParam (eg Hotspot_Raster), without that the query wont run (at least as its currently structured), but we are then effectively disregarding that when it comes to the displaying part on the map which just seems a little odd. 

Anyway I've rejigged my code and moved stuff down into the processGPOutput() and have got the MapService URL outputting in the callback although Im not sure I've quite structured that part right, it's too late at night to think clearly!

Feedback welcome of course :)
Cheers
Rowan

**Comment by jgravois** [comment]
fixed in 9b4917ea95bffb8e6dd0d6403b05aef744b822c8
