### ISSUE TITLE
Callback error but the GP is run correctly

### ISSUE THREAD

**Issue by vtsvitus** [jgravois/esri-leaflet-gp#33]
Hi,
I run a GP (http://geotec.dlsi.uji.es:6080/arcgis/rest/services/dfriasPruebas/GP_Integrate_BR/GPServer/GP_Integrate_BR) is asynchronous. My code is:

```
var gpService= L.esri.GP.service({
    url: 'http://geotec.dlsi.uji.es:6080/arcgis/rest/services/dfriasPruebas/GP_Integrate_BR/GPServer/GP_Integrate_BR',
    useCors: false,
    async: true
});

gpTask = gpService.createTask();

gpTask.run(integrateCallback);

function integrateCallback(error, response, raw){
    alert("Error: "+ error.toString);
}
```

When you run the GP, in the integrateCallback you receive an an error of object, response and raw are null. The code of error is 400 and the message: "Unable to complete operation"., but my jobStatus is 'esriJobSucceeded' and he runs correctly. 

I haven't got output parameters in my GP.

**Comment by jgravois** [comment]
when i click [Submit Job (GET)](http://geotec.dlsi.uji.es:6080/arcgis/rest/services/dfriasPruebas/GP_Integrate_BR/GPServer/GP_Integrate_BR/submitJob), passing the default strings to your geoprocessing service, it fails.

if you're able to walk me through what's required to get the job to succeed directly at the REST endpoint, i'd be better equipped to help you debug your problem in Leaflet.

**Comment by vtsvitus** [comment]
I'm sorry, since my house the GP doesn't work, but since this my job yes, is by the token, this is a token for you, is available for 5 days:

     Token: xqSgZcR6-0y7BFU5-oMNFhl5yWPcD98i4R0KegsCSUM2STCyIqL8mVd74XZ8gse10TaFzb9xAnJHzF8_ZDlp1RKyV6WjXBmvefUoBXE5L_DHEe1b_2H1EA8tvP33VN_d4V7sgA33OAQYCmOyPUO0WkwVAZx04VbU1wPJgAyPGo8.

I alone have to execute my GP, the results are the same that information to inputs

**Comment by vtsvitus** [comment]
I'm sorry, since my house the GP doesn't work, but since this my job yes, is by the token, this is a token for you, is available for 5 days:

    Token: W4C-SYoZb458LXZfwF-NFoso7HbdD5PpdHBRLVnluU0XO9u0Jgvgj-Hx9tnxxmvnbnSHrE9iP-uZbAkeTLgJWzPxefzlPjsRpteYb6Yb6ThdF-7wohAt9kBuGaE6d1bWte6TSnClRLpLKrmuJXQ0Mz0-mwb8578XAc0nhuCoXhDi0Inc0PI7KviCbIvzRt33

I alone have to execute my GP, the results are the same that information to inputs

**Comment by vtsvitus** [comment]
I'm sorry, since my house the GP doesn't work, but since this my job yes, is by the token, this is a token for you, is available for 5 days:

     Token: ayw_lpCBNKkePgRwSWv2KYB2IUELH6I1j9wv2Q49VlZC4U0l0xTAvEtmUzDIA2z0qeXrm6fB0uZ5iyTF1rOUK7IcUnOnZ5DkpWyDDyE03dM.

You must execute it in this URL: http://localhost:63342/ENAbLE/mapRooms.html, because the token is generate for it.

I alone have to execute my GP, the results are the same that information to inputs

**Comment by jgravois** [comment]
i wouldn't be able to view your service url at all if it were protected by token security.  additionally, i'm not able to manually supply your token in a request stemming from [http://localhost:63342/ENAbLE/mapRooms.html] because i've never seen that code.

**Comment by vtsvitus** [comment]
I'm sorry but I must put the token because if don't put it the GP doesn't' work, or you must execute GP since here (how you isn't possible execute since here you should put the token). 

I executed step by step, I am going to trying explain the error:

service.js - line 71

    _createServiceCallback: function (method, path, params, callback, context) {....}

path = "jobs/j9fc73511854a440aa13452c96e30d707/results/undefined"
params = Object {},

Request.js - line 168
    
     return {
       id: callbackId,
       url: script.src,
       abort: function () {
        window._EsriLeafletCallbacks._callback[callbackId]({
         code: 0,
         message: 'Request aborted.'
        });
      }
     };
    }


url = "jobs/j9fc73511854a440aa13452c96e30d707/results/undefined"

service.js  - line 29

    request: function (path, params, callback, context) {
    return this._request('request', path, params, callback, context);
    },

path = "jobs/j9fc73511854a440aa13452c96e30d707/results/undefined"

service.js line 106

     this.fire('requestsuccess', {
          url: this.options.url + path,
          params: params,
          response: response,
          method: method
        }, true);
      }

response = Object {jobId: "j9fc73511854a440aa13452c96e30d707", jobStatus: "esriJobSucceeded", results: Object, inputs: Object, messages: Array[0]}


request.js line 161

      callback.call(context, error, response);

error = undefined, response = Object {jobId: "j9fc73511854a440aa13452c96e30d707", jobStatus: "esriJobSucceeded", results: Object, inputs: Object,  messages: Array[0]


    window._EsriLeafletCallbacks.c3({"jobId":"j9fc73511854a440aa13452c96e30d707","jobStatus":"esriJobSucceeded","results":{},"inputs":{"school_boundary":{"paramUrl":"inputs/school_boundary"},"school_rooms":{"paramUrl":"inputs/school_rooms"}},"messages":[]});

    window._EsriLeafletCallbacks.c4({"error":{"code":400,"message":"Unable to complete operation.","details":[]}});

Request.js - line 146

    window._EsriLeafletCallbacks[callbackId] = function (response) {

response = Object {error: Object}

Request.js - line 156 

       if (!error && response.error) {
        error = response;
        response = null;
      }

For this is error, but the process and execution the GP is correctly

I think that the problem is in output parameters, because this exit is null or undefined, that is empty. It could not evaluate this case. I don't see more, because I can't go into to code.

I hope I have explained myself well

**Comment by vtsvitus** [comment]
I'm sorry but I must put the token because if don't put it the GP doesn't' work, or you must execute GP since here (how you isn't possible execute since here you should put the token). 

I executed step by step, I am going to trying explain the error:

service.js - line 71

    _createServiceCallback: function (method, path, params, callback, context) {....}

path = "jobs/j9fc73511854a440aa13452c96e30d707/results/undefined"
params = Object {},

Request.js - line 168
    
     return {
       id: callbackId,
       url: script.src,
       abort: function () {
        window._EsriLeafletCallbacks._callback[callbackId]({
         code: 0,
         message: 'Request aborted.'
        });
      }
     };
    }


url = "jobs/j9fc73511854a440aa13452c96e30d707/results/undefined"

service.js  - line 29

    request: function (path, params, callback, context) {
    return this._request('request', path, params, callback, context);
    },

path = "jobs/j9fc73511854a440aa13452c96e30d707/results/undefined"

service.js line 106

     this.fire('requestsuccess', {
          url: this.options.url + path,
          params: params,
          response: response,
          method: method
        }, true);
      }

response = Object {jobId: "j9fc73511854a440aa13452c96e30d707", jobStatus: "esriJobSucceeded", results: Object, inputs: Object, messages: Array[0]}


request.js line 161

      callback.call(context, error, response);

error = undefined, response = Object {jobId: "j9fc73511854a440aa13452c96e30d707", jobStatus: "esriJobSucceeded", results: Object, inputs: Object,  messages: Array[0]


    window._EsriLeafletCallbacks.c3({"jobId":"j9fc73511854a440aa13452c96e30d707","jobStatus":"esriJobSucceeded","results":{},"inputs":{"school_boundary":{"paramUrl":"inputs/school_boundary"},"school_rooms":{"paramUrl":"inputs/school_rooms"}},"messages":[]});

    window._EsriLeafletCallbacks.c4({"error":{"code":400,"message":"Unable to complete operation.","details":[]}});

Request.js - line 146

    window._EsriLeafletCallbacks[callbackId] = function (response) {

response = Object {error: Object}

Request.js - line 156 

       if (!error && response.error) {
        error = response;
        response = null;
      }

For this is error, but the process and execution the GP is correctly

I think that the problem is in output parameters, because this exit is null or undefined, that is empty. It could not evaluate this case. I don't see more, because I can't go into to code.

I hope I have explained myself well

**Comment by jgravois** [comment]
sorry its just too hard to try and follow you blow by blow without being able to run the code myself.

i will need access to a public geoprocessing service which does **not** throw errors when called directly from REST if i'm going to be able to try and help debug problems from within code that calls the plugin.
