### ISSUE TITLE
task.run callback param called on loop if esriJobFailed with async gp task

### ISSUE THREAD

**Issue by jfolds** [jgravois/esri-leaflet-gp#38]
I recently noticed a failing gp task.run method was firing the callback on a loop. I tracked down the issue to https://github.com/jgravois/esri-leaflet-gp/blob/master/src/Tasks/Geoprocessing.js#L183

If I move `window.clearInterval(counter);` above `callback.call(context, 'Job Failed', null);` it seems to fix the issue. Wasn't sure if there is a better way to handle this though.

Chrome Version 55.0.2883.87 m (64-bit)
Windows 10

**Comment by jgravois** [comment]
thanks for the report!

> If I move `window.clearInterval(counter);` above `callback.call(context, 'Job Failed', null);` it seems to fix the issue.

it seems strange to me that the current order of operations is problematic, but i'm happy to take a look. i just need to find a public async sample service and generate a request that induces a failure.

**Comment by jfolds** [comment]
Yes, very strange. I just tried to create a test example and cannot reproduce the issue. In my environment, any code after the `callback.call(context, 'Job Failed', nulll);` line will not run.

**Comment by jfolds** [comment]
Closing this, it was an issue within my callback preventing the code from executing. Sorry, thanks!

**Comment by jgravois** [comment]
no worries! thanks for looping back.
