### ISSUE TITLE
POST geometry?

### ISSUE THREAD

**Issue by ahalota** [jgravois/esri-leaflet-gp#40]
Not sure if this is the code or me misusing it...

Trying to use this for one of the ESRI provided services that come with any Image Service as of 10.4, "computeStatisticsHistograms".

My code looks like this:
```
var gpService = L.esri.GP.service({
		url: myImageServiceUrl+ "/computeStatisticsHistograms"
	});
	var gpTask = gpService.createTask();	
	gpTask.setParam("geometryType", "esriGeometryPolygon");

        var esriPoly = {"rings":[[[-149.52,64.277],[-149.52,64.48],[-148.53,64.48],
                                            [-148.53,64.27]]],
                                "spatialReference":{"wkid":"4326"}}
	gpTask.setParam("geometry", esriPoly);
	gpTask.run(function(error, geojson, response){
            console.log(error);
            console.log(geojson);
            console.log(response);
        });
```

I tested this out on the form provided at the image service url, and it works fine. When I run it through the javascript code with this plugin though, I get this error: "Syntax error in JSON geometry representation esri arcserver".
I checked my network traffic, and it looks like it sends a GET request, and my geometry gets mangled into the following url: 

https://[[myImageServiceURL]]/computeStatisticsHistograms/execute?geometryType=esriGeometryPolygon&geometry=%7B%22geometryType%22%3A%22%22%2C%22features%22%3A%5B%5D%7D&f=json

Definitely something going wrong here. Is this due to character length limitations on GET? Is there a way to have the plugin make a POST request?

**Comment by jgravois** [comment]
strange timing, but i submitted a PR (#39) yesterday with a new sample that i noticed automatically uses a POST because the request is too long to GET.

i'll try to find a public service to test with and see what the difference is.

**Comment by jgravois** [comment]
i just reread your post and now have a much better idea of what is causing the _mangling_.

this plugin expects input geometries to be passed in either [`L.LatLng`](http://leafletjs.com/reference.html#latlng), [`L.Marker`](http://leafletjs.com/reference.html#marker), [`L.LatLngBounds`](http://leafletjs.com/reference.html#latlngbounds) or [GeoJSON](http://geojson.io/#map=2/20.0/0.0) format and converts them to Esri JSON before making requests. ([ref](http://esri.github.io/esri-leaflet/api-reference/tasks/gp-task.html#methods)) 

when you try to pass Esri JSON. it bombs out.

you may already know this, but the other thing that's going on is just standard browser encoding.  when you copy/paste your own url into [meyerweb](http://meyerweb.com/eric/tools/dencoder/) its easier to see in the decoded url that an empty array of features are being passed.
```
..?geometryType=esriGeometryPolygon&geometry={"geometryType":"","features":[]}&f=json
```

**Comment by jgravois** [comment]
since the GP service you are calling doesn't actually _expect_ an array of features at all, for the time being you're probably best off coercing your original variable to a string to make sure the plugin passes it along unscathed.

```
var stringifiedEsriPoly = '{"rings":[[[-149.52,64.277],[-149.52,64.48],[-148.53,64.48],
    [-148.53,64.27]]], "spatialReference":{"wkid":"4326"}}';
gpTask.setParam("geometry", stringifiedEsriPoly);
```
this is the first GP service i've seen that expects raw geometries. 

i'll chew on it a bit more, but my first instinct is that it would be a passable *solution* to check internally to see if a param named `geometryType` has already been set and if so, just skip building up the array.

**Comment by ahalota** [comment]
I tried out both of those solutions, neither works. I'll just make a simple jQuery post request instead, but FYI here's the errors I'm seeing:

With your first suggestion, I used `gpTask.setParam("geometry", myShape.toGeoJSON());`
 and got the same error as before. My decoded url looked like this:

https://myImageService/ImageServer/computeStatisticsHistograms/execute?geometryType=esriGeometryPolygon&geometry={"geometryType":"esriGeometryPolygon","features":[{"geometry":{"rings":[[[-146.35,64.09],[-146.35,64.21],[-145.83,64.21],[-145.83,64.09],[-146.35,64.09]]],"spatialReference":{"wkid":4326}}}]}&f=json

Compared to the functional url from the service:
https://myImageService/ImageServer/computeStatisticsHistograms/execute?geometryType=esriGeometryPolygon&geometry={"rings":[[[-146.35,64.09],[-146.35,64.21],[-145.83,64.21],[-145.83,64.09],[-146.35,64.09]]],"spatialReference":{"wkid":4326}}&f=json

So yeah, looks like something in the formatting doesn't pick up quite right, your latest suggestion for the code change could work since it seems this standard service no longer matches the format you were expecting.

----------

Using your stringifiedEsriPoly, I get this error in the console:

```Geoprocessing.js:198 Uncaught TypeError: Cannot read property 'length' of undefined
    at e.processGPOutput (Geoprocessing.js:198)
    at e.<anonymous> (Geoprocessing.js:162)
    at e.<anonymous> (Service.js:96)
    at XMLHttpRequest.s.onreadystatechange (Request.js:75)
```
BUT the network shows it is sending a request to the valid URL at least (similar to the second one shown above)

**Comment by jgravois** [comment]
thanks for the feedback @ahalota. i've created a pull request (#41) to attempt to resolve these issues for others in the future that includes a canned sample which shows the ImageService i used to generate my histograms.

if you could spare the time to kick the tires yourself, i'd feel a lot more comfortable merging it and tagging a new release.  going forward, i _really_ need to write some unit tests.

**Comment by jgravois** [comment]
i went ahead and tagged `v2.0.2` with the fix.  if you see any problems with it, please let me know.
