### ISSUE TITLE
How to define the input parameters of GPRecordSet?

### ISSUE THREAD

**Issue by Giserwu** [jgravois/esri-leaflet-gp#43]
Hello jgravois!
I would like to consult when using the esri-leaflet to call the GP service when the parameter format is GPFeatureRecordSetLayer can be defined as GeoJSON, but when the parameter format is GPRecordSet, how to define the input parameters? Would you please give me a complete example of several different parameter calls? 
@jgravois   Thank you!
![34374704-5c805e64-eb1d-11e7-897c-5e8479603602](https://user-images.githubusercontent.com/23161877/34410996-d9517562-ec0e-11e7-8fd3-0443eeb2a94f.jpg)

**Comment by jgravois** [comment]
hello! there's no need to `@` mention individuals when logging GitHub issues. maintainers and other folks watching the repo are already notified about new posts.

i'll find some time to help you in the next couple days. in the meantime, what have you already tried?

**Comment by jgravois** [comment]
i took a look this afternoon and realized there was a logic error in the plugin that prevented collections of GeoJSON features without geometry from being converted and passed through as input parameters.

fabcd82726aceb0c2e4ffeefdcc1c0a0383cdea6 has been bundled in [`v2.0.3`](https://github.com/jgravois/esri-leaflet-gp/releases/tag/v2.0.3). 

the simple app below demonstrates the fix in action. happy to chat more if you have more questions.

https://johngravois.com/esri-leaflet-gp/demos/vrp.html

**Comment by Giserwu** [comment]
Thank you!!! I learned a lot from here, the problem is solved! Thank you for your help!!!!!
