### ISSUE TITLE
update elevation profile example to display results in a chart

### ISSUE THREAD

**Issue by tomwayson** [jgravois/esri-leaflet-gp#6]
FYI - I was testing C3 as a way to draw an elevation profile for another project, and used your elevation profile example as a way of generating some data, so I thought I'd share that back w/ you.

http://jsfiddle.net/tomwayson/6zc07mr9/

You need to set the include the M values param when you make the request to the GP service, and then you parse the M and Z values out of the response to use as inputs to the chart. If we end up going this route and implementing it, I could make a PR to your example if you're interested.

**Comment by jgravois** [comment]
this is *really* cool!   you're almost reading my mind because i forked [cedar](http://github.com/esridc/cedar) yesterday with the intention of getting more comfortable mashing up charts and maps.

PR away, but i'm happy to help too as i think it would make a really solid addition.

**Comment by tomwayson** [comment]
Cool. As you can tell that fiddle is missing the code to parse the feature in the response. If we go forward with this, then I'll have something I can PR (if you haven't already come up w/ something).

**Comment by jgravois** [comment]
closed via c3a9b28cab8ce77f565aa452329e367df965dcbd
